apiVersion: v1
kind: Service
metadata:
  labels:
    app: block-buster
  name: block-buster-service
  namespace: 1-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: block-buster
    version: 7.1.0
    env: dev
  type: LoadBalancer
